### ISSUE TITLE
Move away from dato cms to github and markdown

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/writers#13]
**Why**: Nobody is updating the cms, as it is quite different than the rest of the content which is using Github, moving to GH would also allow to have a workflow such as create -> Review -> merge, etc.
Everyone in GSF needs to learn how to work with the github merge.
**What**: Migrate
- Articles (priority 1) - **in December**
- Projects (priority 2)
- Logos (priority 3)
- All other pages (priority 4)

**Scope of work**
- [x] #19
- [ ] Rebuild the website to use Github and **markdown** as content management solution (as speakers)
- [ ] Research how to handle previews (before it's merged) - e.g. make a URL for each PR so that it can be previewed
- [ ] Handle translations - (https://greensoftware.foundation/articles/the-green-software-foundation-releases-alpha-version-of-software-carbon-intensity is URL of ENG version, the JP version should have https://greensoftware.foundation/jp/articles/the-green-software-foundation-releases-alpha-version-of-software-carbon-intensity) so that google knows that it's a translation and link the SEO together
- [ ] TBC
- [ ] Document the process for how other people would be able to do it

**Acceptance criteria**:
- People can submit, review (preview if possible) and approve via github
