### ISSUE TITLE
Develop Monthly Content Calendar

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#210]
What: Calendar of determined and planned content published by the GSF
Why: Get a better understanding of the scope of work, nature of content being shared and identify any gaps or areas for improvement and increased collaboration 

[Calendar](https://docs.google.com/spreadsheets/d/1TkU-x79UFtqM1FsckqR-8BKJuaSKQazIekoGOcBFsxw/edit#gid=0) | [Kanban View](https://github.com/orgs/Green-Software-Foundation/projects/22/views/2)

### ISSUES BY MONTH

**January**

- [ ] [Scaling Green Software Culture – A Grassroots Approach Blossoms for Avanade](https://greensoftware.foundation/articles/scaling-green-software-culture-a-grassroots-approach-blossoms-for-avanade)
- [ ] [Baselining Software Carbon Emissions - A Use Case by UBS](https://greensoftware.foundation/articles/baselining-software-carbon-emissions-ubs-use-case)
- [ ] [Creating Technology with Purpose - Meet Carolin Rubner, Head of Research Group at Siemens](https://greensoftware.foundation/articles/creating-technology-with-purpose-meet-carolin-rubner-head-of-research-group-at-si)

**February**

- [ ] [Green Software Foundation and SustainableIT.org Partner for Sustainable Software Development](https://docs.google.com/document/d/1DhesGlQaqZtiYe0_697LajvH3lwGux8h3gfUflbCfcE/edit)
- [ ] [Sustainability as a Primary Integrated Requirement for Software - Meet Mauro Caporuscio, Professor of Computer Science at Linnaeus University](https://greensoftware.foundation/articles/sustainability-as-a-primary-integrated-requirement-for-software-meet-mauro-caporu)
- [ ] [Green Software Foundation Announces New Leadership Appointments: Sanjay Podder Takes Helm as Chair, Chris Lloyd-Jones Elected as Vice Chair](https://greensoftware.foundation/articles/green-software-foundation-announces-new-leadership-appointments-sanjay-podder-tak)

**March**

- [ ] [Insights from GS Patterns Workshop](https://github.com/Green-Software-Foundation/writers/issues/187)
- [ ] [Measuring for Action Versus Measuring for Reporting](https://github.com/Green-Software-Foundation/writers/issues/30)
- [ ] [GSF Summit - What to Expect, Where!](https://github.com/Green-Software-Foundation/writers/issues/181)
- [ ] [Carbon Hack Pre-Event Press Release](https://github.com/Green-Software-Foundation/carbonhack-event/issues/260)
- [ ] [Why we endorsed the Environmental Impact of AI Act](https://github.com/Green-Software-Foundation/writers/issues/212)
- [ ] [Understanding the Environmental Footprint of our Digital Activities - Meet Ahmad Antar, Digital Emissions](https://github.com/Green-Software-Foundation/writers/issues/207)
- [ ] [Carbon Aware SDK Graduation](https://github.com/Green-Software-Foundation/writers/issues/213)

**April**

- [ ] GSMM Article 
- [ ] [MBTI Interview](https://github.com/Green-Software-Foundation/writers/issues/162)
- [ ] [Completed the Green Software Practitioners course? Now what?](https://github.com/Green-Software-Foundation/writers/issues/62)
- [ ] [Carbon Hack 24 Key Highlights and Winners](https://github.com/Green-Software-Foundation/writers/issues/208)
- [ ] [Introducing Accelerated Projects](https://github.com/Green-Software-Foundation/writers/issues/176)

**May**

- [ ] [DXC Member Interview](https://github.com/Green-Software-Foundation/writers/issues/161)
- [ ] [Marginal vs. Average - what's the debate all about?](https://github.com/Green-Software-Foundation/writers/issues/170)
- [ ] [Bloomberg Interview](https://github.com/Green-Software-Foundation/writers/issues/163)
- [ ] [GSP Series Article #2: Product Leads](https://github.com/Green-Software-Foundation/writers/issues/178)
- [ ] [Introducing the Vendor Directory](https://github.com/Green-Software-Foundation/writers/issues/177)

**June**

- [ ] [Official Schedule for GSF Global Summit 2024, and Everything You Need to Know ](https://github.com/Green-Software-Foundation/writers/issues/209)
- [ ] [Integrating Green Software Training into your Sustainability Learning Platforms](https://github.com/Green-Software-Foundation/writers/issues/139)
- [ ] [GSF Summit Closing Ceremony Highlights](https://github.com/Green-Software-Foundation/writers/issues/211)
- [ ] [GSP Series #3: UX UI Designers](https://github.com/Green-Software-Foundation/writers/issues/179)

**July**

- [ ] [A scorecard for processes and features](https://github.com/Green-Software-Foundation/writers/issues/104)
- [ ] [Book Launch interview "Building Green Software"](https://github.com/Green-Software-Foundation/writers/issues/109)
- [ ] [GSP Series #4: Software Architects](https://github.com/Green-Software-Foundation/writers/issues/180)

**Comment by NAMRATA-WOKE** [comment]
@zanete @jawache @russelltrow @Sophietn @seanmcilroy29

**Comment by jawache** [comment]
Thanks @NAMRATA-WOKE this is great, really transparent!

To work with the weekly planning process can you make smaller milestone issues for each month, just the current/next month is fine. In each issue put links to the articles for that month.

This way the theory we have is that we will pay attention to the articles coming out soon. By seeing one issue for everything we suspect we'll just eventually learn to glance over it and not have that trigger to delve in and learn what's happening this month.

Makes sense?

**Comment by NAMRATA-WOKE** [comment]
@zanete is there a way to automate it this based on the date set for each issue in the writer's repo? Otherwise, it sounds like I'll have to duplicate the information in the excel sheet manually. I like using excel for this sort of stuff because it's easier to see more information at a glance. Happy to duplicate but will need a few more days! :)

**Comment by zanete** [comment]
@NAMRATA-WOKE there is probably a way to automate if you used Notion instead of spreadsheet, maybe we can connect notion to your spreadsheet (with the help of the notion expert). Are you sing Excel or google spreadsheets?

**Comment by NAMRATA-WOKE** [comment]
Using google spreadsheet but can export to Excel if we can automate!

**Comment by russelltrow** [comment]
@jawache @NAMRATA-WOKE to discuss the creation of monthly milestone article issues

**Comment by NAMRATA-WOKE** [comment]
@ursvill take a look at what's going on here.

**Comment by russelltrow** [comment]
@NAMRATA-WOKE to break calendar down into individual GH issues e.g. March 2024, April 2024
