### ISSUE TITLE
March-2024 Content Calendar

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#215]
- [x] [Carbon Hack Pre-Event Press Release](https://github.com/Green-Software-Foundation/carbonhack-event/issues/260)
- [x] [Why we endorsed the Environmental Impact of AI Act](https://github.com/Green-Software-Foundation/writers/issues/212)
- [x] [HARC Q&A Article](https://docs.google.com/document/d/1DLGNVrW_SqxhaOAOkUQljhhwSlT6MDVL/edit)
- [x] [CAST Software Case Study](https://github.com/Green-Software-Foundation/sci-guide/issues/60)

**Comment by NAMRATA-WOKE** [comment]
@Sophietn is it reasonable to target March 26 for the CASDK graduation article?

**Comment by Sophietn** [comment]
Yes, so long as I can get ahold of Vaughan the PL

**Comment by NAMRATA-WOKE** [comment]
CASDK article pushed to April
